### ISSUE TITLE
TODO: User session management

### ISSUE THREAD

**Issue by bjlee** [alexcazerne/ploem#1]
- [ ] flask 서버에 user session 기능 구현하기 (flask-login plugin  사용?)
- [ ] 자체 회원 가입 인터페이스
- [ ] facebook, google+ 등 인증 인터페이스
- [ ] login/logout/user setting 인터페이스
